name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c9ec3b885312c4e953ae4719adbe197e75059955b0e3a5354710065513599a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
