name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e62b747dac5aeb1194db0d94db2dea899caa319706348a3ec4076653d9e50e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
