name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb4989d60dd11ecf7333ec2584b8fd96da501ae88ef0071e27befc4cbc120680"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
