name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9658f97df4958ee0b0e1cf90fa1f1834e91af651728b60120559fbafe0599a5d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
