name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75ad5039a1204897129279f92c6ec400ef3efa0282e17a07bee3ae238407c813"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
