name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffd4163483eae4a94fea897b4c23036283935d33384eda31fedbcf92519ad0d2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
