name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee1072d233aec8eb3b838faf260d197669ec75fc4c56682337c65fe1a7df277b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
