name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76ba368d2e75c2b74511f1f2012cebe6f475e1c91e3b2719e351d3414b5261bc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
